# Generated by Django 5.0.7 on 2024-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('about_on_project', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Proposals',
            },
        ),
    ]
