# Generated by Django 5.0.7 on 2024-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='Service/image/')),
                ('description', models.TextField()),
            ],
        ),
    ]
